In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords

In [2]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
df = pd.read_csv('/content/aggregated_reviews.csv', index_col=0)

In [4]:
df.head()

,Place_ID,Place_Name,cleaned_reviews
0,ChIJ-1OO3xhZei4RpiUw_jIlPBQ,TUGU LOR,berada di jalan am sangaji atau lebih tepat da...
1,ChIJ-2etA9ABey4RU42x6nFD9WU,Angkringan Baniyah & Gaza Barbershop,tempat nya asyik tempat nyaman mantap
2,ChIJ-7bqq6lXei4RhCzUxYM12Yg,Angkringan Pak Sugeng,lumayan cukup komplit sesuai kantong di masa p...
3,ChIJ-S-FxAZbei4Rdf1ECy_-xNE,Bilbil Juice Aneka jus buah,langganan banget jus buah tidak abal rasa harg...
4,ChIJ-UhWzNZbei4Rd1P09xwuUY0,Es Coklat Bon@ng.262 Prambanan,coklat enak manis pas dan berasa asli coklat r...

## Remove More Stopwords

In [5]:
indo = stopwords.words('indonesian')

In [6]:
def remove_stopwords(text, stopwords):
    words = text.split()
    filtered_words = [word for word in words if word not in stopwords]
    filtered_text = ' '.join(filtered_words)
    return filtered_text

In [7]:
indo.extend(["tidak", "agak", 'aada', 'ini', 'itu', 'jadi', 'cafe', 'coba', 'atau', 'banget', 'kalau', 'karena', 'ke', 'lah', 'lain', 'mau', 'nya', 'sangat', 'sama'])
indo.extend(['masih', 'seperti', 'sampai', 'tapi', 'untuk', 'tetapi', 'lain', 'cuma', 'dari', 'dalam', 'buat', 'bisa', 'juga', 'saja', 'saya', 'sih', 'ya', 'satu'])
indo.extend(['indo', 'bikin', 'orang', 'salah', 'ribu', 'yoyakarta', 'yogyakarta', 'kesini', 'ha', 'beli', 'sayang', 'deh', 'kayak', 'kali', 'buka', 'sebelah', 'the', 'pakai'])
indo.extend(['mas', 'mbak', 'it', 'overall', 'hehe'])

In [8]:
df.cleaned_reviews = df.cleaned_reviews.apply(lambda x: remove_stopwords(x, indo))

## TF-IDF

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html

max_df is used for removing terms that appear too frequently, also known as "corpus-specific stop words". For example:

max_df = 0.50 means "ignore terms that appear in more than 50% of the documents".
max_df = 25 means "ignore terms that appear in more than 25 documents".
The default max_df is 1.0, which means "ignore terms that appear in more than 100% of the documents". Thus, the default setting does not ignore any terms.

min_df is used for removing terms that appear too infrequently. For example:

min_df = 0.01 means "ignore terms that appear in less than 1% of the documents".
min_df = 5 means "ignore terms that appear in less than 5 documents".
The default min_df is 1, which means "ignore terms that appear in less than 1 document". Thus, the default setting does not ignore any terms.

max_features = build a vocabulary that only consider the top max_features ordered by term frequency across the corpus. Otherwise, all features are used.

In [9]:
# Instantiate the vectorizer object and transform the plot column
vectorizer = TfidfVectorizer(max_df=0.8, min_df=2, max_features = 150)
vectorized_data = vectorizer.fit_transform(df['cleaned_reviews']) 

# Create Dataframe from TF-IDFarray
tfidf_df = pd.DataFrame(vectorized_data.toarray(), columns=vectorizer.get_feature_names_out())

# Assign the movie titles to the index and inspect
tfidf_df.index = df['Place_ID']

In [10]:
tfidf_df.columns[:100]

Index(['ac', 'adem', 'ambil', 'anak', 'area', 'asyik', 'ayam', 'bagus',
       'bakar', 'bakmi', 'bareng', 'barista', 'beragam', 'bersih', 'bumbu',
       'camilan', 'cepat', 'cocok', 'coffee', 'colokan', 'cozy', 'daging',
       'duduk', 'enak', 'es', 'fasilitas', 'favorit', 'foto', 'goreng',
       'gudeg', 'gurih', 'habis', 'harga', 'indoor', 'jalan', 'jam', 'jawa',
       'kafe', 'kantong', 'kasih', 'keluarga', 'kemarin', 'kencang', 'keren',
       'khas', 'konsep', 'kopi', 'kota', 'kuah', 'kursi', 'langsung', 'lantai',
       'lauk', 'lengkap', 'lesehan', 'live', 'lokasi', 'luas', 'lumayan',
       'lupa', 'mahal', 'mahasiswa', 'makan', 'makanan', 'malam', 'mampir',
       'manis', 'mantap', 'masakan', 'masuk', 'meja', 'menarik', 'mencoba',
       'mengobrol', 'menikmati', 'menu', 'menunggu', 'mie', 'minum', 'minuman',
       'mobil', 'motor', 'muda', 'mudah', 'murah', 'musala', 'musik', 'nasi',
       'nih', 'nongkrong', 'nugas', 'nyaman', 'oke', 'outdoor', 'pagi',
       'panas', 'parkir', 'parkiran', 'pas', 'pedas'],
      dtype='object')

In [11]:
tfidf_df.columns[100:]

Index(['pelayanan', 'pengunjung', 'pesan', 'pilihan', 'pinggir', 'pokok',
       'porsi', 'ramah', 'ramai', 'recomended', 'recommended', 'resto',
       'ringan', 'ruangan', 'rumah', 'sambal', 'santai', 'sate', 'sayur',
       'segar', 'sesuai', 'siang', 'sore', 'soto', 'spot', 'standar',
       'strategis', 'suasana', 'suka', 'super', 'susu', 'teh', 'telur',
       'teman', 'tempe', 'tenang', 'terima', 'terjangkau', 'tersedia',
       'toilet', 'tugas', 'tugu', 'ugm', 'unik', 'varian', 'view', 'wajib',
       'warung', 'wifi', 'worth'],
      dtype='object')

In [12]:
tfidf_df

,ac,adem,ambil,anak,area,asyik,ayam,bagus,bakar,bakmi,...,tugas,tugu,ugm,unik,varian,view,wajib,warung,wifi,worth
Place_ID,,,,,,,,,,,,,,,,,,,,,
ChIJ-1OO3xhZei4RpiUw_jIlPBQ,0.0,0.239419,0.000000,0.000000,0.182633,0.055952,0.000000,0.024794,0.000000,0.0,...,0.0,0.091401,0.0,0.118086,0.036297,0.000000,0.000000,0.000000,0.0,0.0
ChIJ-2etA9ABey4RU42x6nFD9WU,0.0,0.000000,0.000000,0.000000,0.000000,0.694969,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
ChIJ-7bqq6lXei4RhCzUxYM12Yg,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
ChIJ-S-FxAZbei4Rdf1ECy_-xNE,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
ChIJ-UhWzNZbei4Rd1P09xwuUY0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.319903,0.0,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ChIJz8b_3FFnei4RyQzP4v9c3nM,0.0,0.000000,0.270156,0.000000,0.000000,0.000000,0.176143,0.000000,0.278061,0.0,...,0.0,0.000000,0.0,0.022372,0.000000,0.000000,0.000000,0.063760,0.0,0.0
ChIJzRJJzqIBey4Rb_-C8fFfHKM,0.0,0.000000,0.000000,0.000000,0.215714,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.265004,0.0,0.0
ChIJzXaqSjJYei4RYf7_5RITA9Y,0.0,0.000000,0.000000,0.000000,0.000000,0.207851,0.000000,0.184212,0.000000,0.0,...,0.0,0.000000,0.0,0.000000,0.000000,0.411319,0.000000,0.000000,0.0,0.0
ChIJzdIkjZxZei4RgAq0Zm4aqic,0.0,0.000000,0.000000,0.423181,0.000000,0.000000,0.188909,0.000000,0.000000,0.0,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
ChIJzfDAL5JXei4RB_2bokRgwJ0,0.0,0.087617,0.000000,0.000000,0.000000,0.061429,0.000000,0.217770,0.000000,0.0,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.075812,0.000000,0.0,0.0

## Cosine Similarity

In [13]:
# Import cosine_similarity measure
from sklearn.metrics.pairwise import cosine_similarity

# Create the array of cosine similarity values
cosine_similarity_array = cosine_similarity(tfidf_df)

# Wrap the array in a pandas DataFrame
cosine_similarity_df = pd.DataFrame(cosine_similarity_array, index=tfidf_df.index, columns=tfidf_df.index)

This is suitable for recommending places in the bottom section of place details.

In [14]:
# Print the top 5 rows of the DataFrame
cosine_similarity_df.head()

Place_ID,ChIJ-1OO3xhZei4RpiUw_jIlPBQ,ChIJ-2etA9ABey4RU42x6nFD9WU,ChIJ-7bqq6lXei4RhCzUxYM12Yg,ChIJ-S-FxAZbei4Rdf1ECy_-xNE,ChIJ-UhWzNZbei4Rd1P09xwuUY0,ChIJ-VZXtXdZei4R87hWiz5QC3A,ChIJ-XQW5GRZei4Rqo3-9FJkZ34,ChIJ-YSIVXJXei4RruOW9y8zbV4,ChIJ-YsB5eJaei4R4u9P73I8J3E,ChIJ-dg2e55bei4R2NFzQbFGu80,...,ChIJycBiwr5Zei4Rhd7p2_cW6Zw,ChIJyeEZeL5Xei4RoqmIq02SNkE,ChIJyff7yXVXei4RgIxBaCM9e2c,ChIJyzl7G_1Xei4RPn7I1meS0rU,ChIJz8NNJzpYei4R9Wh7rwSq9cY,ChIJz8b_3FFnei4RyQzP4v9c3nM,ChIJzRJJzqIBey4Rb_-C8fFfHKM,ChIJzXaqSjJYei4RYf7_5RITA9Y,ChIJzdIkjZxZei4RgAq0Zm4aqic,ChIJzfDAL5JXei4RB_2bokRgwJ0
Place_ID,,,,,,,,,,,,,,,,,,,,,
ChIJ-1OO3xhZei4RpiUw_jIlPBQ,1.000000,0.096471,0.269423,0.052897,0.212137,0.338097,0.166734,0.039259,0.201776,0.250161,...,0.364485,0.134982,0.282421,0.630335,0.438664,0.244191,0.414049,0.288705,0.070533,0.413232
ChIJ-2etA9ABey4RU42x6nFD9WU,0.096471,1.000000,0.000000,0.143758,0.000000,0.120314,0.000000,0.000000,0.013417,0.162882,...,0.288355,0.028892,0.118835,0.201113,0.196066,0.048236,0.136034,0.218160,0.000000,0.088390
ChIJ-7bqq6lXei4RhCzUxYM12Yg,0.269423,0.000000,1.000000,0.000000,0.000000,0.021893,0.000000,0.000000,0.022385,0.078114,...,0.075748,0.038334,0.134088,0.213149,0.113404,0.027976,0.310944,0.027803,0.000000,0.114734
ChIJ-S-FxAZbei4Rdf1ECy_-xNE,0.052897,0.143758,0.000000,1.000000,0.040073,0.199924,0.000000,0.000000,0.040333,0.281476,...,0.120859,0.071862,0.119611,0.170427,0.109857,0.106970,0.039483,0.039695,0.059644,0.070891
ChIJ-UhWzNZbei4Rd1P09xwuUY0,0.212137,0.000000,0.000000,0.040073,1.000000,0.285787,0.198815,0.169750,0.192921,0.338035,...,0.266550,0.230762,0.070629,0.267892,0.203084,0.247545,0.022155,0.080530,0.037579,0.238956

In [15]:
# Find the values for the place with specific ID : ChIJz8b_3FFnei4RyQzP4v9c3nM	(Warung Makan Restu Ibu	)
cosine_similarity_series = cosine_similarity_df.loc['ChIJz8b_3FFnei4RyQzP4v9c3nM']

# Sort these values highest to lowest
ordered_similarities = cosine_similarity_series.sort_values(ascending=False)

# Print the results
print(ordered_similarities)

Place_ID
ChIJz8b_3FFnei4RyQzP4v9c3nM    1.000000
ChIJdTyDMeZZei4RlRet81pF5KY    0.791688
ChIJf9MAObRZei4RUew1n52hm94    0.788387
ChIJbbKlBQdbei4RZHMyjwkJYGQ    0.732685
ChIJ236W0kdZei4R-ADtGTXSdO8    0.668787
                                 ...
ChIJK267UEYBey4RamHV9IVnTQ4    0.000000
ChIJ__OA4J3lei4RHlfB85vTctc    0.000000
ChIJSQwX1GJRei4R_34D8-GBghk    0.000000
ChIJW3YBzrhZei4R1BDCDA3cHh8    0.000000
ChIJjU9NTCRYei4RJMKv7vPCTyg    0.000000
Name: ChIJz8b_3FFnei4RyQzP4v9c3nM, Length: 357, dtype: float64

# Recommendation based on user preferences

In [16]:
df.Place_Name[30:45]

30                Coldhans Coffee Uny
31    Kantin Aldhan Fak. Filsafat UGM
32       Rumah Makan Padang Prambanan
33              Toegoe Coffee and Tea
34               Lesehan Tasik Malaya
35           Bercanda Coffee & Eatery
36     De Djogdja Karaoke Lounge Cafe
37                 Omah Kayu Wonosari
38                 Angkringan Farmasi
39           Inggar Food And Beverage
40                          Kopi Tugu
41                       Hen's Coffee
42                     House of Kijoy
43                      Mamahké Jogja
44                          Slide Bar
Name: Place_Name, dtype: object

## Rekomendasi Andi Budi

In [17]:
tfidf_df = tfidf_df[~tfidf_df.index.duplicated()]

In [18]:
list_of_favorite_place_ids = ['ChIJVRf53J8Aey4R6HeAu6FrEuM', 'ChIJkZPCGp8Aey4RvxeFSsPS5W0', 'ChIJ_WKkLNxXei4R7Jh9_wrcp9U', 'ChIJyff7yXVXei4RgIxBaCM9e2c','ChIJ12iZq5ZXei4RgQuh1QR2C3c']

# Create a subset of only the user favorite places
favorite_places_df = tfidf_df.reindex(list_of_favorite_place_ids)

# Inspect the DataFrame
favorite_places_df

,ac,adem,ambil,anak,area,asyik,ayam,bagus,bakar,bakmi,...,tugas,tugu,ugm,unik,varian,view,wajib,warung,wifi,worth
Place_ID,,,,,,,,,,,,,,,,,,,,,
ChIJVRf53J8Aey4R6HeAu6FrEuM,0.0,0.000000,0.0,0.091663,0.000000,0.147750,0.000000,0.065473,0.0,0.0,...,0.000000,0.0,0.0,0.103941,0.000000,0.0,0.0,0.000000,0.00000,0.00000
ChIJkZPCGp8Aey4RvxeFSsPS5W0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.176255,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.00000,0.00000
ChIJ_WKkLNxXei4R7Jh9_wrcp9U,0.0,0.000000,0.0,0.000000,0.000000,0.166978,0.000000,0.036997,0.0,0.0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.055797,0.00000,0.00000
ChIJyff7yXVXei4RgIxBaCM9e2c,0.0,0.000000,0.0,0.000000,0.000000,0.170993,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.00000,0.00000
ChIJ12iZq5ZXei4RgQuh1QR2C3c,0.0,0.036494,0.0,0.000000,0.055677,0.000000,0.000000,0.045353,0.0,0.0,...,0.071518,0.0,0.0,0.035999,0.066393,0.0,0.0,0.000000,0.24996,0.03227

In [19]:
# Calculate the mean
user_prof = favorite_places_df.mean()

In [20]:
# Find subset of tfidf_df that does not include places in list_of_favorite_place_ids
tfidf_subset_df = tfidf_df.drop(list_of_favorite_place_ids, axis=0)

# Calculate the cosine_similarity and wrap it in a DataFrame
similarity_array = cosine_similarity(user_prof.values.reshape(1, -1), tfidf_subset_df)
similarity_df = pd.DataFrame(similarity_array.T, index=tfidf_subset_df.index, columns=["similarity_score"])

# Sort the values from high to low by the values in the similarity_score
sorted_similarity_df = similarity_df.sort_values(by="similarity_score", ascending=False)

# Reset the Index
sorted_similarity_df = sorted_similarity_df.reset_index()

In [21]:
# Inspect the most similar to the user preferences
sorted_similarity_df.head(10)

                      Place_ID  similarity_score
0  ChIJAd_fLEOzey4REvhX95u2-sc          0.692053
1  ChIJz8NNJzpYei4R9Wh7rwSq9cY          0.691697
2  ChIJgbfOZjRYei4RgtVB5W3lH2g          0.673059
3  ChIJc2Jhi9hNei4Rq5WuZ7BpZ8M          0.670023
4  ChIJKVwqYEWzey4RD5JYvOOOGgE          0.665475
5  ChIJbc2bgURYei4RAw8upAxTexE          0.660664
6  ChIJtVoSXVyzey4RVZsXBV4FdD0          0.630214
7  ChIJfauYPNlXei4Rs97XEt6Cihw          0.624599
8  ChIJ_UA7yZlZei4RLDHFeBI4vEM          0.623085
9  ChIJycBiwr5Zei4Rhd7p2_cW6Zw          0.621325

In [22]:
recommended_places = [df.loc[df['Place_ID'] == ID, 'Place_Name'].values[0] for ID in sorted_similarity_df.Place_ID]

In [23]:
recommended_places[:10]

['Mrikiniki Angkringan And Gallery',
 'Sakapatat Social House & Resto',
 'Coklat Cafe',
 'Tempat ngopi',
 "Kandang ogut's",
 'Liquid Bar And Kitchen',
 "d'TEKO",
 'Semanak Coffee & Eatery',
 'Sunyi Coffee Jogja',
 'Nyore Coffee & Space']

## Rekomendasi Caca Dina

In [24]:
tfidf_df = tfidf_df[~tfidf_df.index.duplicated()]

In [25]:
list_of_favorite_place_ids = ['ChIJJdrijK8Bey4RLJd-873sz5w', 'ChIJl6tDx8dZei4RfA88ffLXnDc', 'ChIJx9si9MVZei4R7k80s8E6a3Q', 'ChIJp4drRkhYei4RD0sGJEwVJLw','ChIJzXaqSjJYei4RYf7_5RITA9Y']

# Create a subset of only the user favorite places
favorite_places_df = tfidf_df.reindex(list_of_favorite_place_ids)

# Inspect the DataFrame
favorite_places_df

,ac,adem,ambil,anak,area,asyik,ayam,bagus,bakar,bakmi,...,tugas,tugu,ugm,unik,varian,view,wajib,warung,wifi,worth
Place_ID,,,,,,,,,,,,,,,,,,,,,
ChIJJdrijK8Bey4RLJd-873sz5w,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
ChIJl6tDx8dZei4RfA88ffLXnDc,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
ChIJx9si9MVZei4R7k80s8E6a3Q,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
ChIJp4drRkhYei4RD0sGJEwVJLw,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.144495,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.268863,0.0,0.0,0.199095,0.0
ChIJzXaqSjJYei4RYf7_5RITA9Y,0.0,0.0,0.0,0.0,0.0,0.207851,0.0,0.184212,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.411319,0.0,0.0,0.000000,0.0

In [26]:
# Calculate the mean
user_prof = favorite_places_df.mean()

In [27]:
# Find subset of tfidf_df that does not include places in list_of_favorite_place_ids
tfidf_subset_df = tfidf_df.drop(list_of_favorite_place_ids, axis=0)

# Calculate the cosine_similarity and wrap it in a DataFrame
similarity_array = cosine_similarity(user_prof.values.reshape(1, -1), tfidf_subset_df)
similarity_df = pd.DataFrame(similarity_array.T, index=tfidf_subset_df.index, columns=["similarity_score"])

# Sort the values from high to low by the values in the similarity_score
sorted_similarity_df = similarity_df.sort_values(by="similarity_score", ascending=False)

# Reset the Index
sorted_similarity_df = sorted_similarity_df.reset_index()

In [28]:
# Inspect the most similar to the user preferences
sorted_similarity_df.head(10)

                      Place_ID  similarity_score
0  ChIJ7d_nCsBZei4R4nM70A44-UE          0.561419
1  ChIJa4xFOZNZei4RddSVY-39S8s          0.542527
2  ChIJQ2aVkI9Xei4RnZIJFH9yaN8          0.539936
3  ChIJKVwqYEWzey4RD5JYvOOOGgE          0.521906
4  ChIJHfSeNgNZei4RT3WiyG3HX_U          0.520895
5  ChIJFW9moyZYei4RyydF4VnJZgw          0.511302
6  ChIJxbpgRkhYei4Ri0J5gvxo4CE          0.511270
7  ChIJbc2bgURYei4RAw8upAxTexE          0.493348
8  ChIJycBiwr5Zei4Rhd7p2_cW6Zw          0.483695
9  ChIJZ2c-RxK1ey4RPYqaToDztJ8          0.481673

In [29]:
recommended_places = [df.loc[df['Place_ID'] == ID, 'Place_Name'].values[0] for ID in sorted_similarity_df.Place_ID]

In [30]:
recommended_places[:10]

['Mucho Cafe & Bar',
 'Goodwin Bar and Eatery',
 'Pendopo Lawas',
 "Kandang ogut's",
 'Barley and Barrel',
 'Lucifer',
 'Eboni Bar And Lounge',
 'Liquid Bar And Kitchen',
 'Nyore Coffee & Space',
 'Angkringan iva']

## Rekomendasi Esty Farah

In [31]:
tfidf_df = tfidf_df[~tfidf_df.index.duplicated()]

In [32]:
list_of_favorite_place_ids = ['ChIJlUDN8zBYei4RQ1NeDlgcJu0', 'ChIJ51nfgEFZei4RJwcTMc5VXW4', 'ChIJbc2bgURYei4RAw8upAxTexE', 'ChIJHytZNZRZei4RRbqBOVA3qW8','ChIJd7M66J1Zei4RVqoL_YKHkeg']

# Create a subset of only the user favorite places
favorite_places_df = tfidf_df.reindex(list_of_favorite_place_ids)

# Inspect the DataFrame
favorite_places_df

,ac,adem,ambil,anak,area,asyik,ayam,bagus,bakar,bakmi,...,tugas,tugu,ugm,unik,varian,view,wajib,warung,wifi,worth
Place_ID,,,,,,,,,,,,,,,,,,,,,
ChIJlUDN8zBYei4RQ1NeDlgcJu0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
ChIJ51nfgEFZei4RJwcTMc5VXW4,0.000000,0.0,0.0,0.000000,0.0,0.289345,0.0,0.256438,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000
ChIJbc2bgURYei4RAw8upAxTexE,0.063235,0.0,0.0,0.110017,0.0,0.221670,0.0,0.039292,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.054715,0.0,0.0,0.055916
ChIJHytZNZRZei4RRbqBOVA3qW8,0.000000,0.0,0.0,0.000000,0.0,0.138660,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.089951,0.0,0.000000,0.0,0.0,0.000000
ChIJd7M66J1Zei4RVqoL_YKHkeg,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.833792,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000

In [33]:
# Calculate the mean
user_prof = favorite_places_df.mean()

In [34]:
# Find subset of tfidf_df that does not include places in list_of_favorite_place_ids
tfidf_subset_df = tfidf_df.drop(list_of_favorite_place_ids, axis=0)

# Calculate the cosine_similarity and wrap it in a DataFrame
similarity_array = cosine_similarity(user_prof.values.reshape(1, -1), tfidf_subset_df)
similarity_df = pd.DataFrame(similarity_array.T, index=tfidf_subset_df.index, columns=["similarity_score"])

# Sort the values from high to low by the values in the similarity_score
sorted_similarity_df = similarity_df.sort_values(by="similarity_score", ascending=False)

# Reset the Index
sorted_similarity_df = sorted_similarity_df.reset_index()

In [35]:
# Inspect the most similar to the user preferences
sorted_similarity_df.head(10)

                      Place_ID  similarity_score
0  ChIJHfSeNgNZei4RT3WiyG3HX_U          0.710957
1  ChIJycBiwr5Zei4Rhd7p2_cW6Zw          0.681557
2  ChIJa4xFOZNZei4RddSVY-39S8s          0.666605
3  ChIJFW9moyZYei4RyydF4VnJZgw          0.659812
4  ChIJ7d_nCsBZei4R4nM70A44-UE          0.655806
5  ChIJd76-x3pZei4RmOP4SiDA1sE          0.652299
6  ChIJdz5d9yNYei4RWuToEFCOXoQ          0.652299
7  ChIJ9bs_E2Bbei4RGFSws7jwgxg          0.645604
8  ChIJuT8N7kIBey4R0ABbRM91MtM          0.645604
9  ChIJAd_fLEOzey4REvhX95u2-sc          0.620165

In [36]:
recommended_places = [df.loc[df['Place_ID'] == ID, 'Place_Name'].values[0] for ID in sorted_similarity_df.Place_ID]

In [37]:
recommended_places[:10]

['Barley and Barrel',
 'Nyore Coffee & Space',
 'Goodwin Bar and Eatery',
 'Lucifer',
 'Mucho Cafe & Bar',
 'Bar',
 'TapHouse Beer Garden',
 'Q & Q Karaoke',
 "Rilax's karoke",
 'Mrikiniki Angkringan And Gallery']